namespace mongo_serialization;
table Tag {
  key:[ubyte];
  val:[ubyte];
}
enum ValueType:byte { Long = 0, Double = 1 }
table Item {
  seriesId:[ubyte];

  measurement_name:[ubyte];
  tags:[Tag];
  field_name:[ubyte];

  timestamp_nanos:long;

  value_type:ValueType;
  long_value:long;
  double_value:double;
}
root_type Item;
