kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "tsbs.fullname" . }}
  labels:
    app: {{ include "tsbs.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentVolume.size | quote }}