global:
      scrape_interval:     10s
      evaluation_interval: 10s
scrape_configs:
  - job_name: pushgateway
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090', 'localhost:9100', 'localhost:9101']
remote_write:
  - url: "http://promscale:9201/write"
remote_read:
  - url: "http://promscale:9201/read"
    read_recent: true
